MsgBox "Hola fer", 64, "hola"
MsgBox "Espero que estes bien", 64, "Hola"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"
MsgBox "El que lo lea es gay :v", 64, "El que lo lea es gay :v"